[package]
name = "wesers"
version = "0.3.1"
authors = ["Chiu-Hsiang Hsu <wdv4758h@gmail.com>"]
license = "AGPL-3.0"
readme = "README.rst"
description = "a simple HTTP/HTTPS server in Rust"
repository = "https://github.com/wdv4758h/wesers/"
keywords = ["web", "server"]
build = "build.rs"

[features]
default = []
https = ["iron/ssl"]

[dependencies]
clap = { version = "2.9.1", features = ["yaml"] }
iron = "0.3"
mount = "0.1"
staticfile = "0.2.0"
logger = "0.0.3"
rustc-serialize = "0.3.19"
mustache = "0.7.0"

[build-dependencies]
clap = { version = "2.9.1", features = ["yaml"] }

[profile.release]
lto = true
